In [62]:
import polars as pl
from pathlib import Path
from pprint import pprint

date_suffix = "2023년_12월"

df_master = pl.scan_parquet(f"data/건축물대장_기본개요_{date_suffix}/*")
df_site = pl.scan_parquet(f"data/건축물대장_총괄표제부_{date_suffix}/*")
df_dong = pl.scan_parquet(f"data/건축물대장_표제부_{date_suffix}/*")
df_floor = pl.scan_parquet(f"data/건축물대장_층별개요_{date_suffix}/*")
# df_building_permit_parking = pl.scan_parquet(f"data/건축인허가_주차장_{date_suffix}/*")
# df_housing_permit_parking = pl.scan_parquet(f"data/주택인허가_주차장_{date_suffix}/*")

In [63]:
df_master.columns

['관리_상위_건축물대장_PK',
 '대장_구분_코드',
 '대장_구분_코드_명',
 '대장_종류_코드',
 '대장_종류_코드_명',
 '대지_위치',
 '도로명_대지_위치',
 '건물_명',
 '시군구_코드',
 '법정동_코드',
 '대지_구분_코드',
 '번',
 '지',
 '특수지_명',
 '블록',
 '로트',
 '외필지_수',
 '새주소_도로_코드',
 '새주소_법정동_코드',
 '새주소_지상지하_코드',
 '새주소_본_번',
 '새주소_부_번',
 '지역_코드',
 '지구_코드',
 '구역_코드',
 '지역_코드_명',
 '지구_코드_명',
 '구역_코드_명',
 '생성_일자',
 '관리_건축물대장_PK']

In [64]:
df_site.columns

['대장_구분_코드',
 '대장_구분_코드_명',
 '대장_종류_코드',
 '대장_종류_코드_명',
 '신_구_대장_구분_코드',
 '신_구_대장_구분_코드_명',
 '대지_위치',
 '도로명_대지_위치',
 '건물_명',
 '시군구_코드',
 '법정동_코드',
 '대지_구분_코드',
 '번',
 '지',
 '특수지_명',
 '블록',
 '로트',
 '외필지_수',
 '새주소_도로_코드',
 '새주소_법정동_코드',
 '새주소_지상지하_코드',
 '새주소_본_번',
 '새주소_부_번',
 '대지_면적(㎡)',
 '건축_면적(㎡)',
 '건폐_율(%)',
 '연면적(㎡)',
 '용적_률_산정_연면적(㎡)',
 '용적_률(%)',
 '주_용도_코드',
 '주_용도_코드_명',
 '기타_용도',
 '세대_수(세대)',
 '가구_수(가구)',
 '주_건축물_수',
 '부속_건축물_수',
 '부속_건축물_면적(㎡)',
 '총_주차_수',
 '옥내_기계식_대수(대)',
 '옥내_기계식_면적(㎡)',
 '옥외_기계식_대수(대)',
 '옥외_기계식_면적(㎡)',
 '옥내_자주식_대수(대)',
 '옥내_자주식_면적(㎡)',
 '옥외_자주식_대수(대)',
 '옥외_자주식_면적(㎡)',
 '허가_일',
 '착공_일',
 '사용승인_일',
 '허가번호_년',
 '허가번호_기관_코드',
 '허가번호_기관_코드_명',
 '허가번호_구분_코드',
 '허가번호_구분_코드_명',
 '호_수(호)',
 '에너지효율_등급',
 '에너지절감_율',
 '에너지_EPI점수',
 '친환경_건축물_등급',
 '친환경_건축물_인증점수',
 '지능형_건축물_등급',
 '지능형_건축물_인증점수',
 '생성_일자',
 '관리_건축물대장_PK']

In [65]:
df_dong.columns

['대장_구분_코드',
 '대장_구분_코드_명',
 '대장_종류_코드',
 '대장_종류_코드_명',
 '대지_위치',
 '도로명_대지_위치',
 '건물_명',
 '시군구_코드',
 '법정동_코드',
 '대지_구분_코드',
 '번',
 '지',
 '특수지_명',
 '블록',
 '로트',
 '외필지_수',
 '새주소_도로_코드',
 '새주소_법정동_코드',
 '새주소_지상지하_코드',
 '새주소_본_번',
 '새주소_부_번',
 '동_명',
 '주_부속_구분_코드',
 '주_부속_구분_코드_명',
 '대지_면적(㎡)',
 '건축_면적(㎡)',
 '건폐_율(%)',
 '연면적(㎡)',
 '용적_률_산정_연면적(㎡)',
 '용적_률(%)',
 '구조_코드',
 '구조_코드_명',
 '기타_구조',
 '주_용도_코드',
 '주_용도_코드_명',
 '기타_용도',
 '지붕_코드',
 '지붕_코드_명',
 '기타_지붕',
 '세대_수(세대)',
 '가구_수(가구)',
 '높이(m)',
 '지상_층_수',
 '지하_층_수',
 '승용_승강기_수',
 '비상용_승강기_수',
 '부속_건축물_수',
 '부속_건축물_면적(㎡)',
 '총_동_연면적(㎡)',
 '옥내_기계식_대수(대)',
 '옥내_기계식_면적(㎡)',
 '옥외_기계식_대수(대)',
 '옥외_기계식_면적(㎡)',
 '옥내_자주식_대수(대)',
 '옥내_자주식_면적(㎡)',
 '옥외_자주식_대수(대)',
 '옥외_자주식_면적(㎡)',
 '허가_일',
 '착공_일',
 '사용승인_일',
 '허가번호_년',
 '허가번호_기관_코드',
 '허가번호_기관_코드_명',
 '허가번호_구분_코드',
 '허가번호_구분_코드_명',
 '호_수(호)',
 '에너지효율_등급',
 '에너지절감_율',
 '에너지_EPI점수',
 '친환경_건축물_등급',
 '친환경_건축물_인증점수',
 '지능형_건축물_등급',
 '지능형_건축물_인증점수',
 '생성_일자',
 '내진_설계_적용_여부',
 '내진_능력',
 '관리_건축물대장_PK']

In [66]:
near50 = pl.col("인근_자주식_대수(대)") >= 50

In [67]:
# df_near_building = (
#     df_building_permit_parking.select(
#         [
#             "관리_허가대장_PK",
#             "대지_위치",
#             "시군구_코드",
#             "법정동_코드",
#             "대지_구분_코드",
#             "번",
#             "지",
#             "특수지_명",
#             "블록",
#             "로트",
#             "인근_자주식_대수(대)",
#             "인근_자주식_면적(㎡)",
#             "생성_일자",
#         ]
#     )
#     .filter(near50)
#     .groupby(
#         [
#             "시군구_코드",
#             "법정동_코드",
#             "대지_구분_코드",
#             "번",
#             "지",
#         ]
#     )
#     .agg(
#         [
#             pl.all().sort_by("생성_일자").last(),
#         ]
#     )
#     .collect()
# )
# len(df_near_building)

In [68]:
# df_near_housing = (
#     df_housing_permit_parking.select(
#         [
#             "관리_주택대장_PK",
#             "대지_위치",
#             "시군구_코드",
#             "법정동_코드",
#             "대지_구분_코드",
#             "번",
#             "지",
#             "특수지_명",
#             "블록",
#             "로트",
#             "인근_자주식_대수(대)",
#             "인근_자주식_면적(㎡)",
#             "생성_일자",
#         ]
#     )
#     .filter(near50)
#     .groupby(
#         [
#             "시군구_코드",
#             "법정동_코드",
#             "대지_구분_코드",
#             "번",
#             "지",
#         ]
#     )
#     .agg(
#         [
#             pl.all().sort_by("생성_일자").last(),
#         ]
#     )
#     .collect()
# )
# len(df_near_housing)

인근은 조건을 확인할 수 있는 방법이 없다.

In [69]:
ev_use_excl_apt = [
    "02007",
    "03000",
    "03001",
    "03002",
    "03005",
    "03006",
    "03007",
    "03008",
    "03009",
    "03010",
    "03011",
    "03012",
    "03013",
    "03014",
    "03015",
    "03016",
    "03017",
    "03018",
    "03019",
    "03020",
    "03021",
    "03022",
    "03023",
    "03024",
    "03025",
    "03026",
    "03027",
    "03028",
    "03029",
    "03100",
    "03102",
    "03103",
    "03104",
    "03105",
    "03107",
    "03108",
    "03109",
    "03112",
    "03113",
    "03114",
    "03199",
    "03999",
    "04000",
    "04001",
    "04002",
    "04003",
    "04004",
    "04005",
    "04006",
    "04008",
    "04009",
    "04010",
    "04011",
    "04012",
    "04014",
    "04016",
    "04018",
    "04019",
    "04020",
    "04021",
    "04024",
    "04030",
    "04031",
    "04032",
    "04033",
    "04034",
    "04035",
    "04036",
    "04037",
    "04038",
    "04039",
    "04100",
    "04101",
    "04102",
    "04103",
    "04104",
    "04105",
    "04106",
    "04107",
    "04108",
    "04199",
    "04200",
    "04201",
    "04202",
    "04203",
    "04204",
    "04205",
    "04206",
    "04207",
    "04208",
    "04299",
    "04300",
    "04302",
    "04303",
    "04304",
    "04305",
    "04306",
    "04307",
    "04308",
    "04399",
    "04400",
    "04401",
    "04402",
    "04403",
    "04404",
    "04405",
    "04499",
    "04999",
    "05000",
    "05100",
    "05102",
    "05103",
    "05104",
    "05105",
    "05106",
    "05107",
    "05108",
    "05199",
    "05200",
    "05201",
    "05202",
    "05203",
    "05204",
    "05205",
    "05299",
    "05300",
    "05301",
    "05302",
    "05303",
    "05304",
    "05305",
    "05306",
    "05399",
    "05400",
    "05401",
    "05402",
    "05403",
    "05404",
    "05405",
    "05406",
    "05407",
    "05408",
    "05499",
    "05500",
    "05501",
    "05502",
    "05503",
    "05599",
    "05999",
    "07000",
    "07100",
    "07101",
    "07102",
    "07103",
    "07104",
    "07105",
    "07199",
    "07201",
    "07209",
    "07210",
    "07211",
    "07212",
    "07300",
    "07301",
    "07302",
    "07399",
    "07999",
    "08000",
    "08001",
    "08004",
    "08007",
    "08008",
    "08999",
    "09000",
    "09100",
    "09101",
    "09102",
    "09103",
    "09104",
    "09105",
    "09107",
    "09109",
    "09199",
    "09200",
    "09201",
    "09202",
    "09299",
    "09999",
    "10000",
    "10002",
    "10003",
    "10005",
    "10100",
    "10101",
    "10102",
    "10103",
    "10104",
    "10105",
    "10106",
    "10107",
    "10199",
    "10200",
    "10201",
    "10202",
    "10299",
    "10300",
    "10301",
    "10302",
    "10303",
    "10399",
    "10999",
    "13000",
    "13001",
    "13003",
    "13004",
    "13005",
    "13006",
    "13007",
    "13008",
    "13009",
    "13010",
    "13011",
    "13012",
    "13013",
    "13100",
    "13101",
    "13102",
    "13103",
    "13104",
    "13105",
    "13106",
    "13107",
    "13108",
    "13109",
    "13110",
    "13999",
    "10203",
    "10204",
    "14000",
    "14100",
    "14101",
    "14102",
    "14103",
    "14199",
    "14200",
    "14201",
    "14202",
    "14203",
    "14204",
    "14299",
    "11101",
    "11200",
    "11204",
    "11205",
    "11299",
    "15000",
    "15001",
    "15100",
    "15101",
    "15102",
    "15103",
    "15199",
    "15200",
    "15201",
    "15202",
    "15203",
    "15204",
    "15205",
    "15299",
    "15999",
    "12002",
    "12003",
    "12004",
    "12005",
    "12006",
    "12007",
    "12008",
    "12009",
    "12999",
    "16000",
    "16001",
    "16002",
    "16005",
    "16007",
    "16009",
    "16010",
    "16011",
    "16012",
    "16013",
    "16999",
    "16003",
    "16004",
    "16006",
    "16008",
    "20000",
    "20001",
    "20002",
    "20003",
    "20004",
    "20005",
    "20006",
    "20007",
    "20008",
    "20009",
    "20010",
    "20999",
    "19007",
    "19008",
    "24000",
    "24002",
    "24003",
    "24004",
    "24100",
    "24101",
    "24102",
    "24103",
    "24104",
    "24105",
    "24999",
    "25000",
    "25001",
    "25999",
    "21003",
    "27000",
    "27001",
    "27002",
    "27003",
    "27004",
    "27005",
    "27007",
    "27008",
    "27009",
    "27999",
]

In [70]:
### main part

# hierarchy

# 기본개요에서 건물동(일반건축물대장, 집합대장 표제부) 추출
df_master_building = df_master.select(
    [
        "관리_상위_건축물대장_PK",
        "대장_구분_코드",
        "대장_구분_코드_명",
        "대장_종류_코드",
        "대장_종류_코드_명",
        "대지_위치",
        "도로명_대지_위치",
        "건물_명",
        "시군구_코드",
        "법정동_코드",
        "대지_구분_코드",
        "번",
        "지",
        "관리_건축물대장_PK",
    ]
).filter(
    (
        pl.col("대장_종류_코드").is_in(["2", "3"])
        # & pl.col("관리_상위_건축물대장_PK").is_not_null()
    )
)

df_pk_building = df_master_building.select(
    "관리_상위_건축물대장_PK",
    "관리_건축물대장_PK",
)

df_pk_building_single = df_pk_building.filter(
    pl.col("관리_상위_건축물대장_PK").is_null()
).select("관리_건축물대장_PK")
df_pk_site_complex = (
    df_pk_building.filter(pl.col("관리_상위_건축물대장_PK").is_not_null())
    .select("관리_상위_건축물대장_PK")
    .unique()  # Removes duplicates
    # .rename({"관리_상위_건축물대장_PK": "관리_건축물대장_PK"})  # Renames the column
)

In [71]:
df_pk_building_single.head().collect()

shape: (5, 1)
┌──────────────────────────────┐
│ 관리_건축물대장_PK           │
│ ---                          │
│ str                          │
╞══════════════════════════════╡
│ 0-2998                       │
│ 11110-1000000000000000060121 │
│ 11110-1000000000000000060147 │
│ 11110-1000000000000000060936 │
│ 11110-1000000000000000065286 │
└──────────────────────────────┘

In [72]:
df_pk_site_complex.head().collect()

shape: (5, 1)
┌──────────────────────────────┐
│ 관리_상위_건축물대장_PK      │
│ ---                          │
│ str                          │
╞══════════════════════════════╡
│ 41590-8956                   │
│ 46870-225                    │
│ 44710-1000000000000000841585 │
│ 41287-226924                 │
│ 44230-1000000000000000882273 │
└──────────────────────────────┘

In [73]:
df_site.filter(pl.col("관리_건축물대장_PK") == "36110-5000182149").collect()

shape: (1, 64)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 대장_구분 ┆ 대장_구분 ┆ 대장_종류 ┆ 대장_종류 ┆ … ┆ 지능형_건 ┆ 지능형_건 ┆ 생성_일자 ┆ 관리_건  │
│ _코드     ┆ _코드_명  ┆ _코드     ┆ _코드_명  ┆   ┆ 축물_등급 ┆ 축물_인증 ┆ ---       ┆ 축물대장 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ 점수      ┆ str       ┆ _PK      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 일반      ┆ 1         ┆ 총괄표제  ┆ … ┆ null      ┆ 0         ┆ 20190905  ┆ 36110-50 │
│           ┆           ┆           ┆ 부        ┆   ┆           ┆           ┆           ┆ 00182149 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [74]:
# 하위 표제부 확인
df_master.filter(pl.col("관리_상위_건축물대장_PK") == "36110-5000182149").collect()

shape: (3, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 관리_상위 ┆ 대장_구분 ┆ 대장_구분 ┆ 대장_종류 ┆ … ┆ 지구_코드 ┆ 구역_코드 ┆ 생성_일자 ┆ 관리_건  │
│ _건축물대 ┆ _코드     ┆ _코드_명  ┆ _코드     ┆   ┆ _명       ┆ _명       ┆ ---       ┆ 축물대장 │
│ 장_PK     ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ _PK      │
│ ---       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆           ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 36110-500 ┆ 1         ┆ 일반      ┆ 2         ┆ … ┆ null      ┆ null      ┆ 20191209  ┆ 36110-24 │
│ 0182149   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 982      │
│ 36110-500 ┆ 1         ┆ 일반      ┆ 2         ┆ … ┆ null      ┆ null      ┆ 20191209  ┆ 36110-50 │
│ 0182149   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00066829 │
│ 36110-500 ┆ 1         ┆ 일반      ┆ 2         ┆ … ┆ null      ┆ null      ┆ 20190927  ┆ 36110-50 │
│ 0182149   ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00182150 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [75]:
# building usage code

# df_floor_keyonly = df_floor.select(
#     [
#         "시군구_코드",
#         # "주_용도_코드",
#         # "주_용도_코드_명",
#         "관리_건축물대장_PK",
#     ]
# )

# df_apt = (
#     df_use.filter(pl.col("주_용도_코드") == "02001")
#     .groupby("관리_건축물대장_PK")
#     .first()
# )
# df_apt = df_apt.join(
#     df_master_building.select(
#         [
#             "관리_건축물대장_PK",
#             "관리_상위_건축물대장_PK",
#         ]
#     ),
#     "관리_건축물대장_PK",
#     "left",
# )
# df_apt_complex = df_apt.filter(pl.col("관리_상위_건축물대장_PK").is_not_null())
# df_apt_single = df_apt.filter(pl.col("관리_상위_건축물대장_PK").is_null())

# df_evbuilding = (
#     df_use.filter(pl.col("주_용도_코드").is_in(ev_use_excl_apt))
#     .groupby("관리_건축물대장_PK")
#     .first()
#     .join(
#         df_master_building.select(
#             [
#                 "관리_건축물대장_PK",
#                 "관리_상위_건축물대장_PK",
#             ]
#         ),
#         "관리_건축물대장_PK",
#         "left",
#     )
# )
# df_evbuilding_complex = df_evbuilding.filter(
#     pl.col("관리_상위_건축물대장_PK").is_not_null()
# )
# df_evbuilding_single = df_evbuilding.filter(pl.col("관리_상위_건축물대장_PK").is_null())

In [76]:
col_site = [
    "시군구_코드",
    "주_용도_코드",
    "주_용도_코드_명",
    "세대_수(세대)",
    "총_주차_수",
    "옥내_기계식_대수(대)",
    "옥외_기계식_대수(대)",
    "옥내_자주식_대수(대)",
    "옥외_자주식_대수(대)",
    "사용승인_일",
    "관리_건축물대장_PK",
]

col_dong = [
    "시군구_코드",
    "주_용도_코드",
    "주_용도_코드_명",
    "세대_수(세대)",
    "옥내_기계식_대수(대)",
    "옥외_기계식_대수(대)",
    "옥내_자주식_대수(대)",
    "옥외_자주식_대수(대)",
    "사용승인_일",
    "관리_건축물대장_PK",
]

In [77]:
### apt. with 100 units

# test site df

df_site.filter(pl.col("관리_건축물대장_PK") == "26320-587").select(col_site).collect()

shape: (1, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 시군구_코 ┆ 주_용도_  ┆ 주_용도_  ┆ 세대_수(  ┆ … ┆ 옥내_자주 ┆ 옥외_자주 ┆ 사용승인_ ┆ 관리_건  │
│ 드        ┆ 코드      ┆ 코드_명   ┆ 세대)     ┆   ┆ 식_대수(  ┆ 식_대수(  ┆ 일        ┆ 축물대장 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ 대)       ┆ 대)       ┆ ---       ┆ _PK      │
│ str       ┆ str       ┆ str       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ i64       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 26320     ┆ 02000     ┆ 공동주택  ┆ 532       ┆ … ┆ 251       ┆ 346       ┆ null      ┆ 26320-58 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [78]:
# test dong df

df_master.filter(pl.col("관리_상위_건축물대장_PK") == "26320-587").join(
    df_dong, "관리_건축물대장_PK"
).group_by("관리_상위_건축물대장_PK").agg(
    [
        pl.first("시군구_코드"),
        pl.sum("세대_수(세대)"),
        pl.sum("옥내_기계식_대수(대)"),
        pl.sum("옥외_기계식_대수(대)"),
        pl.sum("옥내_자주식_대수(대)"),
        pl.sum("옥외_자주식_대수(대)"),
        pl.max("사용승인_일"),
    ]
).head(2).collect()

shape: (1, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ 관리_상위_ ┆ 시군구_코  ┆ 세대_수(세 ┆ 옥내_기계 ┆ 옥외_기계 ┆ 옥내_자주 ┆ 옥외_자주 ┆ 사용승인_ │
│ 건축물대장 ┆ 드         ┆ 대)        ┆ 식_대수(  ┆ 식_대수(  ┆ 식_대수(  ┆ 식_대수(  ┆ 일        │
│ _PK        ┆ ---        ┆ ---        ┆ 대)       ┆ 대)       ┆ 대)       ┆ 대)       ┆ ---       │
│ ---        ┆ str        ┆ i64        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│ str        ┆            ┆            ┆ i64       ┆ i64       ┆ i64       ┆ i64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 26320-587  ┆ 26320      ┆ 563        ┆ 0         ┆ 0         ┆ 0         ┆ 0         ┆ 19950527  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

총괄표제부에 주차가 있는 경우, 표제부에는 없는 경우가 있다.

둘을 비교해서 잘 골라야겠지.

그러면 주차는 총 3가지 방식으로 기록될 수 있다.

-   총괄표제부 총 주차 수
-   총괄표제부 옥내옥외기계자주×4
-   일반건축물대장/표제부 옥내옥외기계자주×4

총괄표제부가 없는 일반건축물대장/표제부는 한 가지 방식만 남으므로 그 방식으로 셀 수 있다.

총괄표제부가 있는 일반건축물대장/표제부는 3가지 방식의 비교가 필요하다.

3가지 방식 중 가장 많은 수를 진짜 총 주차 수로 사용한다.

그 외 옥내옥외기계자주×4 주차장 수는 따로 집계한다.

In [122]:
df_site_complex = (
    df_pk_building.filter(pl.col("관리_상위_건축물대장_PK").is_not_null())
    .join(
        df_site.select(col_site),
        left_on="관리_상위_건축물대장_PK",
        right_on="관리_건축물대장_PK",
    )
    .join(df_dong.select(col_dong), "관리_건축물대장_PK", suffix="_dong")
    .with_columns(
        [
            # Calculate sum of indoor/outdoor mechanical and self-driven counts
            (
                pl.col("옥내_기계식_대수(대)")
                + pl.col("옥외_기계식_대수(대)")
                + pl.col("옥내_자주식_대수(대)")
                + pl.col("옥외_자주식_대수(대)")
            ).alias("옥내외_기계자주_대수_합계"),
            (
                pl.col("옥내_기계식_대수(대)_dong")
                + pl.col("옥외_기계식_대수(대)_dong")
                + pl.col("옥내_자주식_대수(대)_dong")
                + pl.col("옥외_자주식_대수(대)_dong")
            ).alias("옥내외_기계자주_대수_합계_dong"),
        ]
    )
    .group_by("관리_상위_건축물대장_PK")
    .agg(
        [
            pl.first("시군구_코드"),
            pl.first("주_용도_코드"),
            pl.first("주_용도_코드_명"),
            pl.col("주_용도_코드_dong").unique(),
            pl.max("세대_수(세대)"),
            pl.sum("세대_수(세대)_dong"),
            pl.max("총_주차_수"),
            pl.max("옥내외_기계자주_대수_합계"),
            pl.max("옥내_기계식_대수(대)"),
            pl.max("옥외_기계식_대수(대)"),
            pl.max("옥내_자주식_대수(대)"),
            pl.max("옥외_자주식_대수(대)"),
            pl.sum("옥내외_기계자주_대수_합계_dong"),
            pl.sum("옥내_기계식_대수(대)_dong"),
            pl.sum("옥외_기계식_대수(대)_dong"),
            pl.sum("옥내_자주식_대수(대)_dong"),
            pl.sum("옥외_자주식_대수(대)_dong"),
            pl.max("사용승인_일"),
            pl.max("사용승인_일_dong"),
        ]
    )
    .with_columns(
        [
            # Find the maximum value from the three methods of parking lot counts
            pl.max_horizontal(
                [
                    pl.col("총_주차_수"),
                    pl.col("옥내외_기계자주_대수_합계"),
                    pl.col("옥내외_기계자주_대수_합계_dong"),
                ]
            ).alias("최종_총_주차_수"),
        ]
    )
)

# .join(
#     df_site.select(col_site), "관리_건축물대장_PK"
# ).with_columns(
#     [
#         # Calculate sum of indoor/outdoor mechanical and self-driven counts
#         (
#             pl.col("옥내_기계식_대수(대)")
#             + pl.col("옥외_기계식_대수(대)")
#             + pl.col("옥내_자주식_대수(대)")
#             + pl.col("옥외_자주식_대수(대)")
#         ).alias("옥내외_기계자주_대수_합계")
#     ]
# )
df_site_complex.filter(pl.col("최종_총_주차_수") >= 10).head().collect()

shape: (5, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 관리_상위 ┆ 시군구_코 ┆ 주_용도_  ┆ 주_용도_  ┆ … ┆ 옥외_자주 ┆ 사용승인_ ┆ 사용승인_ ┆ 최종_총_ │
│ _건축물대 ┆ 드        ┆ 코드      ┆ 코드_명   ┆   ┆ 식_대수(  ┆ 일        ┆ 일_dong   ┆ 주차_수  │
│ 장_PK     ┆ ---       ┆ ---       ┆ ---       ┆   ┆ 대)_dong  ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ str       ┆ i64      │
│ str       ┆           ┆           ┆           ┆   ┆ i64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 44200-100 ┆ 44200     ┆ 17000     ┆ 공장      ┆ … ┆ 12        ┆ 20160204  ┆ 20160204  ┆ 12       │
│ 270229    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 31200-164 ┆ 31200     ┆ 02000     ┆ 공동주택  ┆ … ┆ 102       ┆ null      ┆ 19931203  ┆ 102      │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 41220-100 ┆ 41220     ┆ 03000     ┆ 제1종근린 ┆ … ┆ 0         ┆ 20221214  ┆ 20221214  ┆ 18       │
│ 000000000 ┆           ┆           ┆ 생활시설  ┆   ┆           ┆           ┆           ┆          │
│ 000083660 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 26440-100 ┆ 26440     ┆ null      ┆ null      ┆ … ┆ 64        ┆ 20101020  ┆ 20180608  ┆ 64       │
│ 191212    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 41590-420 ┆ 41590     ┆ 17000     ┆ 공장      ┆ … ┆ 0         ┆ null      ┆ 19940427  ┆ 10       │
│ 6         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [120]:
df_site_complex.filter(pl.col("관리_상위_건축물대장_PK") == "41463-100428554").collect()

shape: (1, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 관리_상위 ┆ 시군구_코 ┆ 주_용도_  ┆ 주_용도_  ┆ … ┆ 옥외_자주 ┆ 사용승인_ ┆ 사용승인_ ┆ 최종_총_ │
│ _건축물대 ┆ 드        ┆ 코드      ┆ 코드_명   ┆   ┆ 식_대수(  ┆ 일        ┆ 일_dong   ┆ 주차_수  │
│ 장_PK     ┆ ---       ┆ ---       ┆ ---       ┆   ┆ 대)_dong  ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ str       ┆ i64      │
│ str       ┆           ┆           ┆           ┆   ┆ i64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 41463-100 ┆ 41463     ┆ 03000     ┆ 제1종근린 ┆ … ┆ 0         ┆ 20190612  ┆ 20190612  ┆ 3        │
│ 428554    ┆           ┆           ┆ 생활시설  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [114]:
df_building_single = df_pk_building_single.join(
    df_dong.select(col_dong), "관리_건축물대장_PK"
).with_columns(
    [
        # Calculate sum of indoor/outdoor mechanical and self-driven counts
        (
            pl.col("옥내_기계식_대수(대)")
            + pl.col("옥외_기계식_대수(대)")
            + pl.col("옥내_자주식_대수(대)")
            + pl.col("옥외_자주식_대수(대)")
        ).alias("최종_총_주차_수")
    ]
)
df_building_single.head().collect()

shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ 관리_건축 ┆ 시군구_코 ┆ 주_용도_  ┆ 주_용도_  ┆ … ┆ 옥내_자주 ┆ 옥외_자주 ┆ 사용승인_ ┆ 최종_총_ │
│ 물대장_PK ┆ 드        ┆ 코드      ┆ 코드_명   ┆   ┆ 식_대수(  ┆ 식_대수(  ┆ 일        ┆ 주차_수  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ 대)       ┆ 대)       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ i64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0-2998    ┆ 0         ┆ 17000     ┆ 공장      ┆ … ┆ 0         ┆ 0         ┆ 19980824  ┆ 0        │
│ 11110-100 ┆ 11110     ┆ 04000     ┆ 제2종근린 ┆ … ┆ 0         ┆ 1         ┆ 20220817  ┆ 1        │
│ 000000000 ┆           ┆           ┆ 생활시설  ┆   ┆           ┆           ┆           ┆          │
│ 000006012 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11110-100 ┆ 11110     ┆ 01000     ┆ 단독주택  ┆ … ┆ 8         ┆ 0         ┆ 20220817  ┆ 8        │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000006014 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11110-100 ┆ 11110     ┆ 04000     ┆ 제2종근린 ┆ … ┆ 1         ┆ 2         ┆ 20220818  ┆ 3        │
│ 000000000 ┆           ┆           ┆ 생활시설  ┆   ┆           ┆           ┆           ┆          │
│ 000006093 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11110-100 ┆ 11110     ┆ 01000     ┆ 단독주택  ┆ … ┆ 2         ┆ 0         ┆ 20220811  ┆ 2        │
│ 000000000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 000006528 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [123]:
col_parking = [
    "시군구_코드",
    "주_용도_코드",
    "주_용도_코드_명",
    "최종_총_주차_수",
    # 기계식, 자주식, 옥내, 옥외 합계가 필요하면 추가 코딩 필요함. 그냥 갖다쓰면 안됨.
]

In [129]:
# Select only the parking-related columns from both dataframes
# and Combine the two dataframes (union operation)
df_combined_parking = pl.concat(
    [df_site_complex.select(col_parking), df_building_single.select(col_parking)]
)

# Create a column to categorize the parking size into ranges (10대, 20대, 50대, 100대)
df_combined_parking = df_combined_parking.with_columns(
    [
        pl.when(pl.col("최종_총_주차_수") <= 10)
        .then(pl.lit("10대 이하"))  # Using pl.lit for literal strings
        .when(pl.col("최종_총_주차_수") <= 20)
        .then(pl.lit("11-20대"))
        .when(pl.col("최종_총_주차_수") <= 50)
        .then(pl.lit("21-50대"))
        .when(pl.col("최종_총_주차_수") <= 100)
        .then(pl.lit("51-100대"))
        .otherwise(pl.lit("100대 이상"))
        .alias("규모_구분")
    ]
)


# Group by 시군구, 용도, 규모 and aggregate the parking lot counts
df_grouped_parking = df_combined_parking.group_by(
    ["시군구_코드", "주_용도_코드", "주_용도_코드_명", "규모_구분"]
).agg(
    [
        pl.sum("최종_총_주차_수").alias("총_주차_대수_합계"),
    ]
)
sido_short = {
    "11": "서울",
    "21": "부산",
    "22": "대구",
    "23": "인천",
    "24": "광주",
    "25": "대전",
    "26": "부산",
    "27": "대구",
    "28": "인천",
    "29": "광주",
    "30": "대전",
    "31": "울산",
    "36": "세종",
    "41": "경기",
    "42": "강원",
    "43": "충북",
    "44": "충남",
    "45": "전북",
    "46": "전남",
    "47": "경북",
    "48": "경남",
    "49": "제주",
    "50": "제주",
    "51": "강원",
}
df_grouped_parking = df_grouped_parking.with_columns(
    [
        pl.col("시군구_코드")
        .str.slice(0, 2)
        .alias("시도_코드"),  # Extract the first two characters
        pl.col("시군구_코드")
        .str.slice(0, 2)
        .replace(sido_short)
        .alias("시도_약칭"),  # Then map 시도_약칭
    ]
)
# Reorder columns to place 시도_코드 and 시도_약칭 as the first columns
df_grouped_parking = df_grouped_parking.select(
    [
        "시도_코드",  # First column
        "시도_약칭",  # Second column
        "시군구_코드",
        "주_용도_코드",
        "주_용도_코드_명",
        "규모_구분",
        "총_주차_대수_합계",
    ]
)
df_grouped_parking.head().collect()

shape: (5, 7)
┌───────────┬───────────┬─────────────┬──────────────┬────────────────┬────────────┬───────────────┐
│ 시도_코드 ┆ 시도_약칭 ┆ 시군구_코드 ┆ 주_용도_코드 ┆ 주_용도_코드_  ┆ 규모_구분  ┆ 총_주차_대수_ │
│ ---       ┆ ---       ┆ ---         ┆ ---          ┆ 명             ┆ ---        ┆ 합계          │
│ str       ┆ str       ┆ str         ┆ str          ┆ ---            ┆ str        ┆ ---           │
│           ┆           ┆             ┆              ┆ str            ┆            ┆ i64           │
╞═══════════╪═══════════╪═════════════╪══════════════╪════════════════╪════════════╪═══════════════╡
│ 27        ┆ 대구      ┆ 27110       ┆ 15000        ┆ 숙박시설       ┆ 10대 이하  ┆ 306           │
│ 41        ┆ 경기      ┆ 41190       ┆ 02000        ┆ 공동주택       ┆ 100대 이상 ┆ 487858        │
│ 46        ┆ 전남      ┆ 46170       ┆ 29000        ┆ 장례시설       ┆ 100대 이상 ┆ 164           │
│ 43        ┆ 충북      ┆ 43760       ┆ 18000        ┆ 창고시설       ┆ 21-50대    ┆ 53            │
│ 29        ┆ 광주      ┆ 29200       ┆ Z8000        ┆ 교육연구및복지 ┆ 10대 이하  ┆ 17            │
│           ┆           ┆             ┆              ┆ 시설           ┆            ┆               │
└───────────┴───────────┴─────────────┴──────────────┴────────────────┴────────────┴───────────────┘

In [131]:
df_grouped_parking.collect().to_pandas().to_csv(
    "output/parking/parking_general.csv", encoding="utf-8-sig", index=False
)

In [138]:
# 시도 코드에 따른 집계
df_sido_grouped = (
    df_grouped_parking.group_by(["시도_코드", "시도_약칭"])
    .agg([pl.sum("총_주차_대수_합계").alias("주차_대수")])
    .sort("시도_코드")
)
df_sido_grouped.collect().to_pandas().to_csv(
    "output/parking/parking_by_sido.csv", encoding="utf-8-sig", index=False
)
df_sido_grouped.head().collect()

shape: (5, 3)
┌───────────┬───────────┬───────────┐
│ 시도_코드 ┆ 시도_약칭 ┆ 주차_대수 │
│ ---       ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ i64       │
╞═══════════╪═══════════╪═══════════╡
│ 0         ┆ 0         ┆ 0         │
│ 11        ┆ 서울      ┆ 7833901   │
│ 26        ┆ 부산      ┆ 5308069   │
│ 27        ┆ 대구      ┆ 3070140   │
│ 28        ┆ 인천      ┆ 4717535   │
└───────────┴───────────┴───────────┘

In [139]:
# 주용도 코드에 따른 집계
df_usage_grouped = (
    df_grouped_parking.group_by(["주_용도_코드", "주_용도_코드_명"])
    .agg([pl.sum("총_주차_대수_합계").alias("주차_대수")])
    .sort("주_용도_코드")
)
df_usage_grouped.collect().to_pandas().to_csv(
    "output/parking/parking_by_usage.csv", encoding="utf-8-sig", index=False
)
df_usage_grouped.head().collect()

shape: (5, 3)
┌──────────────┬─────────────────┬───────────┐
│ 주_용도_코드 ┆ 주_용도_코드_명 ┆ 주차_대수 │
│ ---          ┆ ---             ┆ ---       │
│ str          ┆ str             ┆ i64       │
╞══════════════╪═════════════════╪═══════════╡
│ null         ┆ null            ┆ 735526    │
│ 000          ┆ null            ┆ 0         │
│ 01000        ┆ 단독주택        ┆ 3288934   │
│ 01001        ┆ 단독주택        ┆ 90        │
│ 01002        ┆ 다중주택        ┆ 0         │
└──────────────┴─────────────────┴───────────┘

In [140]:
# 규모 구분에 따른 집계
df_size_grouped = (
    df_grouped_parking.group_by(["규모_구분"])
    .agg([pl.sum("총_주차_대수_합계").alias("주차_대수")])
    .sort("규모_구분")
)
df_size_grouped.collect().to_pandas().to_csv(
    "output/parking/parking_by_size.csv", encoding="utf-8-sig", index=False
)
df_size_grouped.head().collect()

shape: (5, 2)
┌────────────┬───────────┐
│ 규모_구분  ┆ 주차_대수 │
│ ---        ┆ ---       │
│ str        ┆ i64       │
╞════════════╪═══════════╡
│ 100대 이상 ┆ 67895358  │
│ 10대 이하  ┆ 5257607   │
│ 11-20대    ┆ 1772046   │
│ 21-50대    ┆ 2289157   │
│ 51-100대   ┆ 1866011   │
└────────────┴───────────┘